import Risc0.Basic
import Risc0.CompoundTypes
import Risc0.Lemmas
import Risc0.Map
import Risc0.Wheels
import Risc0.Gadgets.IsZero.Constraints.Code
import Risc0.Gadgets.IsZero.Constraints.WeakestPresPart0
import Risc0.Gadgets.IsZero.Constraints.WeakestPresPart1
import Risc0.Gadgets.IsZero.Constraints.WeakestPresPart2
import Risc0.Gadgets.IsZero.Constraints.WeakestPresPart3
import Risc0.Gadgets.IsZero.Constraints.WeakestPresPart4
import Risc0.Gadgets.IsZero.Constraints.WeakestPreFull
import Risc0.Gadgets.IsZero.Witness.Code
import Risc0.Gadgets.IsZero.Witness.WeakestPresPart0
import Risc0.Gadgets.IsZero.Witness.WeakestPresPart1
import Risc0.Gadgets.IsZero.Witness.WeakestPresPart2
import Risc0.Gadgets.IsZero.Witness.WeakestPresPart3
import Risc0.Gadgets.IsZero.Witness.WeakestPresPart4
import Risc0.Gadgets.IsZero.Witness.WeakestPresPart5
import Risc0.Gadgets.IsZero.Witness.WeakestPreFull
import Risc0.Gadgets.IsZero.Proofs
import Risc0.Gadgets.OneHot.Witness.Code
import Risc0.Gadgets.OneHot.Witness.WeakestPresPart0
import Risc0.Gadgets.OneHot.Witness.WeakestPresPart1
import Risc0.Gadgets.OneHot.Witness.WeakestPresPart2
import Risc0.Gadgets.OneHot.Witness.WeakestPresPart3
import Risc0.Gadgets.OneHot.Witness.WeakestPresPart4
import Risc0.Gadgets.OneHot.Witness.WeakestPresPart5
import Risc0.Gadgets.OneHot.Witness.WeakestPresPart6
import Risc0.Gadgets.OneHot.Witness.WeakestPresPart7
import Risc0.Gadgets.OneHot.Witness.WeakestPresPart8
import Risc0.Gadgets.OneHot.Witness.WeakestPreFull
import Risc0.Gadgets.OneHot.Constraints.Code
import Risc0.Gadgets.OneHot.Constraints.WeakestPresPart0
import Risc0.Gadgets.OneHot.Constraints.WeakestPresPart1
import Risc0.Gadgets.OneHot.Constraints.WeakestPresPart2
import Risc0.Gadgets.OneHot.Constraints.WeakestPresPart3
import Risc0.Gadgets.OneHot.Constraints.WeakestPresPart4
import Risc0.Gadgets.OneHot.Constraints.WeakestPresPart5
import Risc0.Gadgets.OneHot.Constraints.WeakestPresPart6
import Risc0.Gadgets.OneHot.Constraints.WeakestPreFull

import Risc0.Gadgets.OneHot20.Witness.Code
import Risc0.Gadgets.OneHot20.Constraints.Code
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart0
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart1
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart2
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart3
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart4
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart5
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart6
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart7
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart8
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart9
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart10
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart11
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart12
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart13
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart14
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart15
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart16
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart17
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart18
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart19
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart20
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart21
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart22
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart23
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart24
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart25
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart26
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart27
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart28
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart29
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart30
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart31
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart32
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart33
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart34
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart35
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart36
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart37
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart38
import Risc0.Gadgets.OneHot20.Constraints.WeakestPresPart39
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart0
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart1
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart2
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart3
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart4
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart5
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart6
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart7
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart8
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart9
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart10
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart11
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart12
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart13
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart14
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart15
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart16
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart17
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart18
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart19
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart20
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart21
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart22
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart23
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart24
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart25
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart26
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart27
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart28
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart29
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart30
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart31
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart32
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart33
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart34
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart35
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart36
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart37
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart38
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart39
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart40
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart41
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart42
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart43
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart44
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart45
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart46
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart47
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart48
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart49
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart50
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart51
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart52
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart53
import Risc0.Gadgets.OneHot20.Witness.WeakestPresPart54